ecr_repo                = "granite-cloud"
environment             = "dev"
git_repo                = "content-eks-deepdive-sample-api-service-go"
git_branch              = "master"
git_owner               = "granite-cloud"
