---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Control Plane'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: EKS Cluster
        Parameters:
          - ClusterName
          - ClusterVersion
          - Environment
          - SubnetIds
          - VPCID

Parameters:
  ClusterName:
    Description: The cluster name provided when the cluster was created.  If it is incorrect, nodes will not be able to join the cluster.
    Type: String

  ClusterVersion:
    Description: Cluster Version
    Type: String
    Default: "latest"
    AllowedValues:
      - "1.11"
      - "1.12"
      - "latest"

  Environment:
    Description: 'Name of the environment for this stack.'
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  SubnetIds:
    Description: 'list of Subnet existing ids where workers can be created.'
    Type: List<AWS::EC2::Subnet::Id>
    ConstraintDescription : 'Must be a list of at least two existing subnets associated with at least two different availability zones.'

  VPCID:
    Description: 'VPC ID.'
    Type: AWS::EC2::VPC::Id
    Description : 'VpcId of your existing Virtual Private Cloud (VPC)'
    ConstraintDescription : 'Must be the VPC Id of an existing Virtual Private Cloud.'

Conditions:
  CreateCustomVersionCluster: !Not [!Equals [!Ref ClusterVersion, latest]]

Resources:
  #####
  # Cluster
  #####
  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ControlPlaneSecurityGroup
        SubnetIds: !Ref SubnetIds
      RoleArn: !GetAtt EksServiceRole.Arn
      # Default version is latest
      Version:
         Fn::If:
          - CreateCustomVersionCluster
          - !Ref ClusterVersion
          - !Ref AWS::NoValue

  #####
  # Security Groups
  #####
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Control Plane Group
      VpcId: !Ref VPCID

  NodeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Node Group
      VpcId: !Ref VPCID
      Tags:
      - Key: !Sub "kubernetes.io/cluster/${ClusterName}"
        Value: 'owned'
      - Key: Name
        Value: !Sub "${ClusterName}-cluster/NodeSecurityGroup"

  #####
  # IAM Role
  #####
  EksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "eks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      # https://medium.com/faun/aws-eks-the-role-is-not-authorized-to-perform-ec2-describeaccountattributes-error-1c6474781b84
      # The below inline policy is to work around a known issue with new eks cluster trying to create an elb the first time.
      # If the below permission is not given the elb will fail to be created with an iam permission error.
      # Note: I have not tested using an ALB ingress yet as this may not apply..
      Policies:
        - PolicyName: describe-accounts-workaround
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: *
                Effect: Allow
                Action:
                  - ec2:DescribeAccountAttributes
      RoleName: !Sub "EksSvcRole-${AWS::StackName}"

Outputs:
  ClusterArn:
    Description: 'EKS Cluster Arn'
    Value: !GetAtt EKSCluster.Arn

  ClusterEndPoint:
    Description: 'EKS Cluster EndPoint'
    Value: !GetAtt EKSCluster.Endpoint

  ClusterName:
    Description: 'EKS Cluster Name'
    Value: !Ref EKSCluster

  ControlSecurityGroup:
    Description: Security group for the cluster control plane
    Value: !Ref ControlPlaneSecurityGroup

  NodeSecurityGroup:
    Description: Security group for the nodes
    Value: !Ref NodeSecurityGroup
