---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Control Plane'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: EKS Cluster
        Parameters:
          - ClusterName
          - ClusterVersion
          - Environment
          - SubnetIds
          - VPCID

Parameters:
  ClusterName:
    Description: The cluster name provided when the cluster was created.  If it is incorrect, nodes will not be able to join the cluster.
    Type: String

  ClusterVersion:
    Description: Cluster Version
    Type: String
    Default: "latest"
    AllowedValues:
      - "1.11"
      - "1.12"
      - "latest"

  Environment:
    Description: 'Name of the environment for this stack.'
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  SubnetIds:
   Description: 'Array of Subnets where workers can be created.'
   Type: List<AWS::EC2::Subnet::Id>

  VPCID:
    Description: 'VPC ID.'
    Type: AWS::EC2::VPC::Id

Conditions:
  CreateCustomVersionCluster: !Not [!Equals [!Ref ClusterVersion, latest]]

Resources:
  #####
  # Cluster
  #####
  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ControlPlaneSecurityGroup
        SubnetIds: !Ref SubnetIds
      RoleArn: !GetAtt EksServiceRole.Arn
      # Default version is latest
      Version:
         Fn::If:
          - CreateCustomVersionCluster
          - !Ref ClusterVersion
          - !Ref AWS::NoValue

  #####
  # Security Groups
  #####
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId: !Ref VPCID

  NodeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for all nodes in the cluster
      VpcId: !Ref VPCID
      Tags:
      - Key: !Sub "kubernetes.io/cluster/${ClusterName}"
        Value: 'owned'
      - Key: Name
        Value: !Sub "${ClusterName}-cluster/NodeSecurityGroup"

  #####
  # IAM Role
  #####
  EksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "eks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      RoleName: !Sub "EksSvcRole-${AWS::StackName}"

Outputs:
  ClusterArn:
    Description: 'EKS Cluster Arn'
    Value: !GetAtt EKSCluster.Arn

  ClusterEndPoint:
    Description: 'EKS Cluster EndPoint'
    Value: !GetAtt EKSCluster.Endpoint

  ClusterName:
    Description: 'EKS Cluster Name'
    Value: !Ref EKSCluster

  ControlSecurityGroup:
    Description: Security group for the cluster control plane
    Value: !Ref ControlPlaneSecurityGroup

  NodeSecurityGroup:
    Description: Security group for the nodes
    Value: !Ref NodeSecurityGroup
