AWSTemplateFormatVersion: '2010-09-09'
Description: 'Parent Stack to create nested stacks for EKS cluster, node group, ASG, lambda, and IAM resources.'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'EKS Configuration'
        Parameters:
          - ClusterName
          - Environment
          - KeyName
          - NodeGroupName
      - Label:
          default: 'Auto Scaling Configuration'
        Parameters:
          - NodeInstanceType
      - Label:
          default: 'VPC Configuration'
        Parameters:
          - SubnetPrivate
          - SubnetPublic
          - VpcCIDR

Parameters:
  ClusterName:
    Description: The name of the eks-cluster that will be provisioned
    Type: String
    Default: eks-cluster

  ClusterVersion:
    Description: Cluster Version
    Type: String
    Default: 'latest'
    AllowedValues:
      - '1.10'
      - '1.11'
      - '1.12'
      - 'latest'

  Environment:
    Description: 'Name of the environment for this stack.'
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - stage
      - prod
    ConstraintDescription: 'Must be a valid environment type.'

  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: String
    Default: 'dev'

  NodeGroupName:
    Description: Unique resource identifier for the Node Group.
    Type: String
    Default: green

  SubnetPublic:
    Description: Comma seperated list of 2 VPC CIDR Blocks for Public Subnets (eg 10.100.2.0/24,10.100.3.0/24)
    Type: CommaDelimitedList
    Default: '10.100.4.0/24,10.100.5.0/24'

  SubnetPrivate:
    Description: Comma seperated list of 3 VPC CIDR Blocks for Private Subnets (eg 10.100.2.0/24,10.100.3.0/24)
    Type: CommaDelimitedList
    Default: '10.100.1.0/24,10.100.2.0/24,10.100.3.0/24'

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: '10.100.0.0/16'

Mappings:
  LayerArn:
    us-east-1:
      kubectl: 'arn:aws:lambda:us-east-1:627177891842:layer:lambda-layer-kubectl:2'
  KubeAdminRole:
    us-east-1:
      kubeadmin: 'arn:aws:iam::627177891842:role/AmazonEKSAdminRole'

Resources:
  # Nested Stacks

  ###########
  # VPC
  ###########
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://granite-eks-playground.s3.amazonaws.com/vpc.yaml'
      Parameters:
        Environment: 'dev'
        SubnetPrivate: !Ref SubnetPrivate
        SubnetPublic: !Ref SubnetPublic
        VpcCIDR: !Ref VpcCIDR

  ###########
  # EKS Cluster
  ###########
  Cluster:
    DependsOn: VPC
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://granite-eks-playground.s3.amazonaws.com/cluster.yaml'
      Parameters:
        ClusterName: !Ref ClusterName
        ClusterVersion: !Ref ClusterVersion
        SubnetIds: !GetAtt VPC.Outputs.SubnetsPrivate
        VPCID: !GetAtt VPC.Outputs.VPC

  ###########
  # EKS Worker Nodes
  ###########
  NodeGroup:
    DependsOn: Cluster
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://granite-eks-playground.s3.amazonaws.com/nodegroup-dev.yaml'
      Parameters:
        ClusterName: !Ref ClusterName
        ControlPlaneSecurityGroup: !GetAtt Cluster.Outputs.ControlSecurityGroup
        KeyName: !Ref KeyName
        NodeSecurityGroup: !GetAtt Cluster.Outputs.NodeSecurityGroup
        NodeGroupName: !Ref NodeGroupName
        SubnetIds: !GetAtt VPC.Outputs.SubnetsPrivate
        VPCID: !GetAtt VPC.Outputs.VPC

  ###########
  # Lambda to add the custom IAM role to the k8's auth config map
  ###########
  ConfigMapLambda:
    DependsOn: NodeGroup
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://granite-eks-playground.s3.amazonaws.com/configmap-sar.yaml'
      Parameters:
        ClusterName: !Ref ClusterName
        LambdaRoleArn: !FindInMap
          - LayerArn
          - !Ref 'AWS::Region'
          - kubectl
        LambdaLayerKubectlArn: !FindInMap
          - KubeAdminRole
          - !Ref 'AWS::Region'
          - kubeadmin
        NodeInstanceRoleArn: !GetAtt NodeGroup.Outputs.NodeInstanceRole
